version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - REPOSITORY_URI=318451290319.dkr.ecr.us-east-1.amazonaws.com//assign
      - IMAGE_TAG=latest
      - CONTAINER_NAME=django
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 318451290319.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 318451290319.dkr.ecr.us-east-1.amazonaws.com/assign .
      #- docker tag assign:latest 318451290319.dkr.ecr.us-east-1.amazonaws.com/assign:latest  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 318451290319.dkr.ecr.us-east-1.amazonaws.com/assign:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json